### ISSUE TITLE
As a user, I should be able to register with my phone number

### ISSUE THREAD

**Issue by omaarr90** [omaarr90/wallet-service#3]
### Brief Description:
This use case for registering new users. This use case starts when a non registered user asks for an account and ends when an account has been created for the user.

### Actros :
- anonymous 
- system storage

### Pre-Conditions:
There should be no user exist with the same info that distinguishes a user from another user.

### Basic Flow:
 1. User input his info
 2. The system validates preconditions.
 3. Generate a username based on the firstname
 4. The system persists user info
 5. System Inform User of successful registration

### Alternative/Exception Flow:
 1a - Ask the User to input the fullname. Can not be empty
 1b - Ask the User to choose another way for the communication channel. an existing account already registered. Ask the user to login with that account by asking him to reset the password (email, phone)

### Post-Conditions:
The user has been registered and his info persists.

The above will be applied regardless of the registration with a phone or an email.

### Technical Detail:
- [ ] wallet_id: UUID

- [ ] fullname: mandatory, this to be a friendly name, "firstname lastname"

- [ ] phone_number: type is Long, starts with 966, and length of 12 chars. This means only Saudi Arabia phone numbers

- [ ] password: hashed password with salt

- [ ] No account exists with the entered phone number.

- [ ] username: username will be generated based on the fullname

- [ ] Generated username should be unique and does not exist for another user.

**Comment by bander-saeed94** [comment]
We will use the phone number all the time. mobile number can be used interchangeably but not in the code.

Fields:
fullname: mandatory, this to be a friendly name, "firstname lastname"
username: username will be generated based on the fullname
phone_numer: type is Long, starts with 966, and length of 12 chars

This inspired by twitter registration.

shall we add email?
if we will add it it will the fields will:
fullname: is optional, this to be a friendly name
username: username will be generated based on the fullname
phone_nume_or_email: type is Long, starts with 966, and length of 12 chars OR email regex

**Comment by omaarr90** [comment]
We will keep it simple for now and only use phone numbers.

**Comment by bander-saeed94** [comment]
Fields:
fullname: mandatory, this to be a friendly name, "firstname lastname"
username: username will be generated based on the fullname
phone_numer: type is Long, starts with 966, and length of 12 chars

for generated username, it will be prefixed with the first name and random number  of 6 digits

**Comment by bander-saeed94** [comment]
Todos,

- [ ] fullname: mandatory, this to be a friendly name, "firstname lastname"

- [ ] phone_numer: type is Long, starts with 966, and length of 12 chars

- [ ] No account exists with the entered phone number.

- [ ] username: username will be generated based on the fullname

- [ ] Generated username should be unique and does not exist for another user.
